spring:
  application:
    name: microservice1

  datasource:
    url: jdbc:mysql://localhost:3306/devdb
    username: devuser
    password: devpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

logging:
  level:
    root: INFO
    com.example: DEBUG

message: "Message from Microservice1 Git config (dev profile), not hardcoded.change"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh
  health:
    db:
      enabled: true
